version: "3.9"

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    command: --model-id /data/llama_finetuned/gptqmodel_4bit --quantize gptq
    ports:
      - "8080:80"
    volumes:
      - ./models:/data:ro
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  rag-api:
    image: phade160/medimaven-rag-api:v1.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
    env_file:
      - .env
    runtime: nvidia
    depends_on:
      - tgi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
