version: "3.9"

services:
  rag-api:
    image: phade160/medimaven-rag-api:1.1.0
    container_name: medimaven-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - ENABLE_MONITORING=true
      - ENABLE_CACHING=true
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - MODEL_DIR=/app/models/v1.1
      # - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./models:/app/models:rw   # Bind mount - container will create ./models if it doesn't exist
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]