project: MediMaven-LTR
program: runs/05_run_ltr_sweep.py
method: grid
metric:
  name: eval_ndcg@10
  goal: maximize
parameters:
  learning_rate:
    values: [0.01, 0.03, 0.1]
  n_estimators:
    values: [50, 100, 200]
  max_depth:
    values: [3, 5, 7]