_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/runs/run_neg_sampling.py
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 55
                - 69
                - 105
            "2":
                - 55
                - 69
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
